config/routes.rb
Rails.application.routes.draw do
  root :to => "blogs#index"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/template/login" => "template#login"
  get "/template/new_feed" => "template#new_feed"
  get "/template/new_feed_people_nearby" => "template#new_feed_people_nearby"
  get "/template/new_feed_friends" => "template#new_feed_friends"
  get "/template/new_feed_messages" => "template#new_feed_messages"
  get "/template/new_feed_find_people" => "template#new_feed_find_people"
  post "/template/new_feed_find_people" => "template#new_feed_find_people"
  get "/template/timeline" => "template#timeline"
  get "/template/timeline_about" => "template#timeline_about"
  get "/template/timeline_album" => "template#timeline_album"
  get "/template/timeline_friends" => "template#timeline_friends"
  get "/users/:id/show_public", to: "users#show_public", as: :show_public
  get "/users/:id/show_private", to: "users#show_private"
  get "/users/:id/show_desire", to: "users#show_desire"
  get "/users/:id/timeline_friends", to: "users#timeline_friends", as: :timeline_friends
  get "posts/new"
  root "users#new"
  resources :blogs
  resources :users
  resources :conections, only: %i(create update destroy)
  resources :reports
  resources :searchs
  resources :complaints

  mount ActionCable.server => "/cable"
  resources :conversations do
    resources :messages, only: %i(index new create)
  end

  get "talk", to: "strangers#index"
  post "talk", to: "strangers#talk"
  post "find", to: "strangers#find"
  post "find_stranger", to: "strangers#find_stranger"
  resources :comments
  resources :transactions, only: %i(index create)

  namespace :admin do
    resources :reports
    resources :complaints
    resources :users, only: %i(index)
    get "unique_reports", to: "reports#show_unique_reports"
  end
end

app/controllers/strangers_controller.rb
class StrangersController < ApplicationController
  before_action :check_blocked_user, :logged_in_user, only: %i(index find_stranger talk)
  before_action :turn_off_matching, only: %i(index)

  def index
    @user = current_user
  end

  def find_stranger
    # Turn on matching
    current_user.turn_on_matching
    # Find matching on stranger
    @stranger = User.where(matching: true).where.not(id: current_user.id).first
    # Notice to owner when stranger join
    if @stranger.present?
      current_user.turn_off_matching
      ActionCable.server.broadcast "user_#{@stranger.id}", matching: true
      # Turn off matching for participant
    end
    # Listen stream
    respond_to do |format|
      format.js {}
    end
  end

  def talk
    isSystem = params.require(:message)[:isSystem]
    stream_of = params.require(:message)[:stream_of]
    @message = Message.new message_params
    # Turn off matching for owner
    if isSystem
      user = User.find @message.user_id
      user.turn_off_matching
    end
    @message_for_sender = render_to_string(
      template: "strangers/_message",
      locals: {message: @message, talking_with_stranger: true},
      layout: false
    )

    @message_for_recipient = render_to_string(
      template: "strangers/_message_recipient",
      locals: {message: @message, talking_with_stranger: true},
      layout: false
    )

    ActionCable.server.broadcast "user_#{stream_of}",
      sender_id: isSystem ? 0 : current_user.id,
      body: @message.body,
      message_for_recipient: @message_for_recipient,
      message_for_sender: @message_for_sender

    respond_to do |format|
      format.js {}
    end
  end

  private

  def get_stranger
    @stranger = User.where(matching: true).where.not(id: current_user.id).first
  end

  def message_params
    params.require(:message).permit(:user_id, :body, :created_at)
  end

  def turn_off_matching
    current_user.turn_off_matching
  end
end

app/views/strangers/_message.html.erb
<li class="<%= message.user_id == current_user.id ? 'right' : 'left' %> w100">
  <% if message.user_id == current_user.id %>
    <%= image_tag("avatar-default.png", class: "profile-photo-sm pull-right") %>
  <% else %>
    <%= image_tag("avatar-default.png", class: "profile-photo-sm pull-left") %>
  <% end %>
  <div class="chat-item">
    <div class="chat-item-header">
      <h5></h5>
      <small class="text-muted"><%= time_ago_in_words(message.created_at) %></small>
    </div>
    <p><%= message.body %></p>
  </div>
</li>

app/views/strangers/_message_form.html.erb
<%= form_for Message.new, url: talk_path, class: "find_stranger_form",
  :format => :js, remote: true do |f| %>
  <%= f.hidden_field(:stream_of, value: stranger.present? ? stranger.id : current_user.id) %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :created_at, value: Time.now %>
  <%= f.text_field :body, class: "form-control", id: "message_field", required: true %>
  <%= f.submit "send", class: "btn btn-primary", id: "message_btn", style: "display: block" %>
<% end %>

app/views/strangers/_message_recipient.html.erb
<li class="<%= message.user_id == current_user.id ? 'left' : 'right' %> w100">
  <% if message.user_id == current_user.id %>
    <%= image_tag("avatar-default.png", class: "profile-photo-sm pull-left") %>
  <% else %>
    <%= image_tag("avatar-default.png", class: "profile-photo-sm pull-right") %>
  <% end %>
  <div class="chat-item">
    <div class="chat-item-header">
      <h5></h5>
      <small class="text-muted"><%= time_ago_in_words(message.created_at) %></small>
    </div>
    <p><%= message.body %></p>
  </div>
</li>

app/views/strangers/find_stranger.js.erb
$(document).ready(function() {
  var started = false;
  var current_user_id = <%= current_user.id %>;
  var stream_of = <%= @stranger.present? ? @stranger.id : current_user.id %>;

  App.strangers = App.cable.subscriptions.create(
  {
    channel: 'StrangersChannel',
    user_id: <%= @stranger.present? ? @stranger.id : current_user.id %>,
  },
  {
    received: function(data) {
      console.log(data);
      // Notice to owner
      if(data.matching == true && started == false) {
        $('#send-message').append('<%= j render "message_form", stranger: @stranger %>');
        $('#stranger_exit_btn').show();
        setTimeout(function(){
          $.ajax({
            url: '/talk',
            headers: {
              'Accept': 'text/javascript, */*; charset=utf-8',
              'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
            },
            type: 'POST',
            data: {
              message : {
                isSystem: true, // For first system's message
                user_id: current_user_id,
                body: '<%= t("strangers.find_stranger.joined_msg") %>',
                stream_of: stream_of,
                created_at: new Date()
              }
            },
          });
          $('.finding').hide();
          $('.edit_user').hide();
        },2000);
        started = true;
      }

      // Notice to participant
      if(data.sender_id != <%= current_user.id %> && started == false) {
        $('.finding').hide();
        $('.edit_user').hide();
        $('#send-message').append('<%= j render "message_form", stranger: @stranger %>');
        $('#stranger_exit_btn').show();
        started = true;
      }

      // Show message
      if(started == true) {
        $('#messages-list').append(this.renderMessage(data));
      }

      // Scroll bottom when a new message appended
      var messages_scrollbar = $('#messages_scrollbar');
      var height = messages_scrollbar[0].scrollHeight;
      messages_scrollbar.scrollTop(height);

      // Clear field after submit
      $('#message_field').val('');
    },

    renderMessage: function(data) {
      var currrent_user_id = $('#chat_room').attr('current-user-id');
      if (data.sender_id == 0) {
        return '<li class="w100"><div class="chat-item"><div class="alert alert-success"><strong>[<%= t("strangers.find_stranger.system") %>]</strong> '+ data.body + '</div></div></li>';
      } else if (currrent_user_id == data.sender_id) {
        return data.message_for_sender;
      }
      return data.message_for_recipient;
    }
  });

  $('#stranger_exit_btn_yes').on('click', function() {
    if (App.strangers) App.cable.subscriptions.remove(App.strangers);
    $.ajax({
      url: '/talk',
      headers: {
        Accept : 'text/javascript; charset=utf-8',
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
      },
      type: 'POST',
      data: {
        message : {
          isSystem: true,
          user_id: current_user_id,
          body: '<%= t("strangers.find_stranger.exit_msg") %>',
          stream_of: stream_of,
          created_at: new Date()
        }
      },
    });
    location.reload();
  })
})

app/views/strangers/index.html.erb
<div id="page-contents">
  <div class="container">
    <div class="row">
      <!-- Newsfeed Common Side Bar Left
      ================================================= -->
      <div class="col-md-3 static">
        <%= render "shared/current_user_profile_card" %>
        <%= render "shared/new_feed_nav_new_feed" %>
      </div>
      <div class="col-md-7">
        <%= render "template/new_feed_post_create_box" %>

        <!-- Chat Room
        ================================================= -->
        <div class="chat-room" id="chat_room" current-user-id="<%= current_user.id %>">
          <div class="row">
            <%= form_for @user, method: :post, url: find_stranger_path,
              remote: true, id: "find_stranger_form" do |f| %>
                <%= f.submit "Find stranger", class: "btn btn-primary pull-left" %>
            <% end %>

            <div class="finding">
              <div class="loader"></div>
              <h4><%= t "strangers.index.finding_msg" %>
              </h4>
            </div>
            <!--Chat Messages in Right-->
            <div class="tab-content scrollbar-wrapper wrapper scrollbar-outer" id="messages_scrollbar">
              <div class="tab-pane active">
                <div class="chat-body">
                  <ul class="chat-message" id="messages-list">

                   </ul>
                </div>
              </div>
            </div><!--Chat Messages in Right End-->

              <div class="send-message" id="send-message">
                <button class="btn btn-danger pull-right" id="stranger_exit_btn" data-toggle="modal" data-target="#exitModal"><%= t "strangers.finder_stanger.exit" %></button>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exitModal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t "strangers.find_stranger.exit_confirm" %></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" data-dismiss="modal" id="stranger_exit_btn_yes">Exit</button>
        <button type="button" class="btn btn-default pull-right" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "strangers" %>