config/routes.rb
Rails.application.routes.draw do
  root :to => "blogs#index"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/template/login" => "template#login"
  get "/template/new_feed" => "template#new_feed"
  get "/template/new_feed_people_nearby" => "template#new_feed_people_nearby"
  get "/template/new_feed_friends" => "template#new_feed_friends"
  get "/template/new_feed_messages" => "template#new_feed_messages"
  get "/template/new_feed_find_people" => "template#new_feed_find_people"
  post "/template/new_feed_find_people" => "template#new_feed_find_people"
  get "/template/timeline" => "template#timeline"
  get "/template/timeline_about" => "template#timeline_about"
  get "/template/timeline_album" => "template#timeline_album"
  get "/template/timeline_friends" => "template#timeline_friends"
  get "/users/:id/show_public", to: "users#show_public", as: :show_public
  get "/users/:id/show_private", to: "users#show_private"
  get "/users/:id/show_desire", to: "users#show_desire"
  get "/users/:id/timeline_friends", to: "users#timeline_friends", as: :timeline_friends
  get "posts/new"
  root "users#new"
  resources :blogs
  resources :users
  resources :conections, only: %i(create update destroy)
  resources :reports
  resources :searchs
  resources :complaints

  mount ActionCable.server => "/cable"
  resources :conversations do
    resources :messages, only: %i(index new create)
  end

  get "talk", to: "strangers#index"
  post "talk", to: "strangers#talk"
  post "find", to: "strangers#find"
  post "find_stranger", to: "strangers#find_stranger"
  resources :comments
  resources :transactions, only: %i(index create)

  namespace :admin do
    resources :reports
    resources :complaints
    resources :users, only: %i(index)
    get "unique_reports", to: "reports#show_unique_reports"
  end
end

app/views/admin/_admin_nav.html.erb
<ul class="nav-news-feed">
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("admin.newfeed"), blogs_path %>
  </div></li>
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("admin.user_all"), admin_users_path %>
  </div></li>
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("admin.reported_all"), admin_reports_path %>
  </div></li>
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("admin.reported_unique"), admin_unique_reports_path  %>
  </div></li>
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("admin.complaint_all"), admin_complaints_path %>
  </div></li>
</ul><!--news-feed links ends-->

app/views/admin/reported.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <div class="profile-card">
      <%= image_tag("users/user-1.jpg", :class => "profile-photo") %>
      <h5><a href="timeline.html" class="text-white">Sarah Cruiz</a></h5>
      <a href="#" class="text-white"><i class="ion ion-android-person-add"></i> 1,299 followers</a>
    </div><!--profile card ends-->
    <%= render "admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th>
            <% if params[:order] == "asc" %>
              <%= link_to t("admin.order"), params.merge(order: "desc") %>
            <% else  %>
              <%= link_to t("admin.order"), params.merge(order: "asc") %>
            <% end %>
          </th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @be_reported_users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <% if user.isBlocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= user.created_at %></td>
            <td><%= user.total %></td>
            <td><%= link_to t(".edit"), edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination -->
    <%= paginate @be_reported_users %>
  </div>
</div>
</div>
</div>

app/views/admin/show.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th>
            <% if params[:order] == "asc" %>
              <%= link_to t("admin.count"), params.merge(order: "desc") %>
            <% else  %>
              <%= link_to t("admin.count"), params.merge(order: "asc") %>
            <% end %>
          </th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @report.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <% if user.isBlocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= image_tag user.avatar_url, class: "profile-photo-admin" %></td>
            <td><%= user.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td><%= user.total %></td>
            <td><%= link_to t(".edit"), edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
</div>

app/views/admin/show_all_reports.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.description" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @be_reported_users.each do |report| %>
          <tr>
            <td><%= report.id %></td>
            <td>
              <% if report.is_blocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= report.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= report.description %></td>
            <td><%= report.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td>
              <%= link_to t("admin.detail"), :controller => "admin", :action => "show", :id => report.user_id %>
              <%= link_to t("edit"), edit_user_path(report.reported_id) %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination -->
    <%= paginate @be_reported_users %>
  </div>
</div>
</div>
</div>

app/views/admin/show_unique_reports.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th>
            <% if params[:order] == "desc" %>
              <%= link_to t("admin.count"), params.merge(order: "asc") %>
            <% else  %>
              <%= link_to t("admin.count"), params.merge(order: "desc") %>
            <% end %>
          </th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @be_reported_users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <% if user.is_blocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= user.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td><%= user.total %></td>
            <td><%= link_to t(".edit"), edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination -->
    <%= paginate @be_reported_users %>
  </div>
</div>
</div>
</div>