config/routes.rb
Rails.application.routes.draw do
  root :to => "blogs#index"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/template/login" => "template#login"
  get "/template/new_feed" => "template#new_feed"
  get "/template/new_feed_people_nearby" => "template#new_feed_people_nearby"
  get "/template/new_feed_friends" => "template#new_feed_friends"
  get "/template/new_feed_messages" => "template#new_feed_messages"
  get "/template/new_feed_find_people" => "template#new_feed_find_people"
  post "/template/new_feed_find_people" => "template#new_feed_find_people"
  get "/template/timeline" => "template#timeline"
  get "/template/timeline_about" => "template#timeline_about"
  get "/template/timeline_album" => "template#timeline_album"
  get "/template/timeline_friends" => "template#timeline_friends"
  get "/users/:id/show_public", to: "users#show_public", as: :show_public
  get "/users/:id/show_private", to: "users#show_private"
  get "/users/:id/show_desire", to: "users#show_desire"
  get "/users/:id/timeline_friends", to: "users#timeline_friends", as: :timeline_friends
  get "posts/new"
  root "users#new"
  resources :blogs
  resources :users
  resources :conections, only: %i(create update destroy)
  resources :reports
  resources :searchs
  resources :complaints

  mount ActionCable.server => "/cable"
  resources :conversations do
    resources :messages, only: %i(index new create)
  end

  get "talk", to: "strangers#index"
  post "talk", to: "strangers#talk"
  post "find", to: "strangers#find"
  post "find_stranger", to: "strangers#find_stranger"
  resources :comments
  resources :transactions, only: %i(index create)

  namespace :admin do
    resources :reports
    resources :complaints
    resources :users, only: %i(index)
    get "unique_reports", to: "reports#show_unique_reports"
  end
end

app/views/shared/_blogs.html.erb
<% if @blogs.empty? %>
  <div class="alert alert-warning">
    <%= t "no_posts_msg" %>
  </div>
<% end %>

<% @blogs.each do |blog| %>
<div class="post-content">
    <%= link_to blog_path(blog) do %>

      <!--Post Date-->
      <div class="post-date hidden-xs hidden-sm">
        <h5><%= blog.user.name %></h5>
        <p class="text-grey"><%= blog.created_at.strftime("%d/%m/%y") %></p>
      </div><!--Post Date End-->

      <% if blog.photo.present? %>
          <%=image_tag blog.photo_url, class: "img-responsive post-image" %>
      <% end %>

      <div class="post-container">
        <%=image_tag blog.user.avatar_url, class: "profile-photo-md pull-left" %>
        <div class="post-detail">
          <div class="user-info">
            <h5>
              <%= link_to blog.user.name, user_path(blog.user), class: "profile-link" %>
              <span class="following">following</span>
            </h5>
            <p class="text-muted"><%= time_ago_in_words(blog.created_at) %> ago</p>
          </div>
          <div class="line-divider"></div>
          <div class="post-text">
            <p><%= blog.body %><i class="em em-anguished"></i> <i class="em em-anguished"></i> <i class="em em-anguished"></i></p>
          </div>
          <div class="line-divider"></div>
        </div>
    </div>
  <% end %>
</div>
<hr>
<% end %>

app/views/shared/_current_user_profile_card.html.erb
<div class="profile-card">
  <%= image_tag current_user.avatar_url(), class: "profile-photo" %>
  <h5>
    <%= link_to current_user.name, user_path(current_user), class: "text-white" %>
  </h5>
</div><!--profile card ends-->

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".content1" %> <%= pluralize(@user.errors.count, t(".error")) %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for :conection, url: conections_path, remote: true do |f| %>
  <%= f.hidden_field :recipient_id, value: @user.id %>
    <%= f.submit t(".add_friend"), class: "btn_sign_up btn btn-sm btn-primary"%>
<% end %>

app/views/shared/_follow_form.html.erb
<div class="follow_form">
  <% if logged_in? && !current_user?(@user) %>
    <% if @follow.present? %>
      <%= render "shared/unfollow" %>
    <% else %>
      <%= render "shared/follow" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_new_feed_blogs.html.erb
<% if @blogs.empty? %>
  <div class="alert alert-warning">
    <%= t "no_posts_msg" %>
  </div>
<% end %>

<% @blogs.each do |blog| %>
<div class="post-content">
    <%= link_to blog_path(blog) do %>
      <% if blog.photo.present? %>
          <%=image_tag blog.photo_url, class: "img-responsive post-image" %>
      <% end %>

      <div class="post-container">
        <%=image_tag blog.user.avatar_url, class: "profile-photo-md pull-left" %>
        <div class="post-detail">
          <div class="user-info">
            <h5>
              <%= link_to blog.user.name, user_path(blog.user), class: "profile-link" %>
              <span class="following">following</span>
            </h5>
            <p class="text-muted"><%= time_ago_in_words(blog.created_at) %> ago</p>
          </div>
          <div class="line-divider"></div>
          <div class="post-text">
            <p><%= blog.body %><i class="em em-anguished"></i> <i class="em em-anguished"></i> <i class="em em-anguished"></i></p>
          </div>
          <div class="line-divider"></div>
        </div>
    </div>
  <% end %>
</div>
<hr>
<% end %>

app/views/shared/_new_feed_nav_new_feed.html.erb
<ul class="nav-news-feed">
  <li><i class="icon ion-ios-paper"></i><div>
    <%= link_to t("newsfeed"), blogs_path %>
  </div></li>
  <li><i class="icon ion-ios-people"></i><div>
    <%= link_to t("matching"), searchs_path %>
  </div></li>
  <li><i class="icon ion-ios-people"></i><div>
    <%= link_to t("people_nearby"), transactions_path %>
  </div></li>
  <li><i class="icon ion-chatboxes"></i><div>
    <%= link_to t("template.chat_with_friends"), conversations_path %>
  </div></li>
  <li><i class="icon ion-chatboxes"></i><div>
    <%= link_to t("template.chat_with_stranger"), talk_path %>
  </div></li>
</ul><!--news-feed links ends-->

app/views/shared/_profile_card.html.erb
<div class="profile-card">
  <%= image_tag @user.avatar_url, class: "profile-photo" %>
  <h5>
    <%= link_to @user.name, user_path(@user), class: "text-white" %>
  </h5>
</div><!--profile card ends-->

app/views/shared/_timeline_activity.html.erb
<% if current_user.id == @user.id %>
  <div id="sticky-sidebar">
    <h4 class="grey"><%= t(".follow_request") %></h4>
    <% if !@wanteds&.any? %>
       <div class="alert alert-warning">
          <%= t "no_request" %>
        </div>
    <% end %>
    <% if logged_in? && current_user.id == @user.id %>
      <% @wanteds&.each do |user| %>
        <div class="feed-item">
        <div class="live-activity">
          <p><%= link_to user.name, user_path(user), class: "profile-link" %> want to follow you.</p>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_timeline_cover.html.erb
<div class="timeline-cover">
  <!--Timeline Menu for Large Screens-->
  <div class="timeline-nav-bar hidden-sm hidden-xs">
    <div class="row">
      <div class="col-md-3">
        <div class="profile-info">
          <%= image_tag @user.avatar_url, class: "img-responsive profile-photo" %>
          <h3><%= @user.name %></h3>
        </div>
      </div>
      <div class="col-md-9">
        <ul class="list-inline profile-menu">
          <li>
            <%= link_to t("timeline"), user_path(@user) %>
          </li>
          <li>
            <%= link_to t("about"), show_public_path(@user) %>
          </li>
          <li>
            <%= link_to t("friends"), timeline_friends_path %>
          </li>
        </ul>
        <ul class="follow-me list-inline">
          <li class="pull-left"><%= render "shared/follow_form" %></li>
          <% if !current_user? @user %>
            <li>
              <!-- Report btn -->
              <button type="button" class="btn btn-danger btn-sm pull-right" data-toggle="modal" data-target="#reportModal"><%= t "users.show.report" %></button>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div><!--Timeline Menu for Large Screens End-->

  <!--Timeline Menu for Small Screens-->
  <div class="navbar-mobile hidden-lg hidden-md">
    <div class="profile-info">
      <%= image_tag @user.avatar_url, class: "img-responsive profile-photo" %>
      <h4><%= @user.name %></h4>
    </div>
    <div class="mobile-menu">
      <ul class="follow-me list-inline">
        <li class=""><%= render "shared/follow_form" %></li>
        <% if !current_user? @user %>
          <li>
            <!-- Report btn -->
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#reportModal"><%= t "users.show.report" %></button>
          </li>
        <% end %>
      </ul>
    </div>
  </div><!--Timeline Menu for Small Screens End-->
</div>

<div id="reportModal" class="modal fade" role="dialog">
  <%= form_for @report, url: reports_path, remote: true do |f| %>
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= t "users.show.report" %></h4>
        </div>
        <div class="modal-body">
            <%= f.label t("users.show.description") %><br>
            <%= f.text_area :description, class: "form-control", required: true %>
            <%= f.hidden_field :reported_id, value: @user.id %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><%= t "close" %></button>
          <%= f.submit "send", class: "btn btn-danger pull-right", id: "message_btn", "data-dismiss" => ""%>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="alert"></div>

app/views/shared/_unfollow.html.erb
<% if @conection.status %>
  <%= form_for :conection, url: conection_path(@conection.id),  method: :delete, remote: true do |f| %>
    <%= f.hidden_field :id, value: @conection.id %>
      <%= f.submit t(".unfriend"), class: "btn_sign_up btn btn-danger btn-sm"%>
  <% end %>
<% else %>
  <% if @conection.recipient_id == @user.id %>
    <%= form_for :conection, url: conection_path(@conection.id),  method: :delete, remote: true do |f| %>
      <%= f.hidden_field :id, value: @conection.id %>
        <%= f.submit t(".pendding"), class: "btn_sign_up btn btn-warning btn-sm"%>
    <% end %>
   <% else %>
    <%= form_for :conection, url: conection_path(@conection.id),  method: :patch, remote: true do |f| %>
      <%= f.hidden_field :id, value: @conection.id %>
        <%= f.submit t(".accept"), class: "btn_sign_up btn btn-success btn-sm"%>
    <% end %>
    <%= form_for :conection, url: conection_path(@conection.id),  method: :delete, remote: true do |f| %>
      <%= f.hidden_field :id, value: @conection.id %>
        <%= f.submit t(".deny"), class: "btn_sign_up btn btn-danger btn-sm"%>
    <% end %>
   <% end %>
<% end %>