config/routes.rb
Rails.application.routes.draw do
  root :to => "blogs#index"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/template/login" => "template#login"
  get "/template/new_feed" => "template#new_feed"
  get "/template/new_feed_people_nearby" => "template#new_feed_people_nearby"
  get "/template/new_feed_friends" => "template#new_feed_friends"
  get "/template/new_feed_messages" => "template#new_feed_messages"
  get "/template/new_feed_find_people" => "template#new_feed_find_people"
  post "/template/new_feed_find_people" => "template#new_feed_find_people"
  get "/template/timeline" => "template#timeline"
  get "/template/timeline_about" => "template#timeline_about"
  get "/template/timeline_album" => "template#timeline_album"
  get "/template/timeline_friends" => "template#timeline_friends"
  get "/users/:id/show_public", to: "users#show_public", as: :show_public
  get "/users/:id/show_private", to: "users#show_private"
  get "/users/:id/show_desire", to: "users#show_desire"
  get "/users/:id/timeline_friends", to: "users#timeline_friends", as: :timeline_friends
  get "posts/new"
  root "users#new"
  resources :blogs
  resources :users
  resources :conections, only: %i(create update destroy)
  resources :reports
  resources :searchs
  resources :complaints

  mount ActionCable.server => "/cable"
  resources :conversations do
    resources :messages, only: %i(index new create)
  end

  get "talk", to: "strangers#index"
  post "talk", to: "strangers#talk"
  post "find", to: "strangers#find"
  post "find_stranger", to: "strangers#find_stranger"
  resources :comments
  resources :transactions, only: %i(index create)

  namespace :admin do
    resources :reports
    resources :complaints
    resources :users, only: %i(index)
    get "unique_reports", to: "reports#show_unique_reports"
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  scope :select_report, -> {
    select("reports.*, users.name as name, users.avatar as avatar,
      users.is_blocked as is_blocked, users.id as user_id")}
  scope :join_with_user, -> {
    joins("INNER JOIN users ON users.id = reports.reported_id")}
  scope :get_unique_reported, -> {
    joins("INNER JOIN users ON users.id = reports.reported_id").
    select("COUNT(reports.reported_id) AS total, users.*").
    group("reports.reported_id, users.id")}
  scope :where_reported_id, ->(reported_id) {
    where("reports.reported_id = ?", reported_id)}
  ATTRIBUTES_PARAMS = %i(user_id reported_id description).freeze
  validates :reported_id, presence: true
  validates :user_id, presence: true
  validates :description, length: {maximum: Settings.maximum.length_report_description}, allow_nil: true
  validates_uniqueness_of :user_id, scope: :reported_id
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController

  def index
    @be_reported_users = Report.join_with_user.select_report.page(params[:page]).per Settings.pagination.report
  end

  def show
    @report = Report.get_unique_reported.where_reported_id(params[:id]).page(params[:page]).per Settings.pagination.report
  end

  def show_unique_reports
    @be_reported_users = Report.get_unique_reported.page(params[:page]).per Settings.pagination.report
    status = params["status"]
    order = params["order"]

    if status == "blocked"
      @be_reported_users = @be_reported_users.where("is_blocked = true");
    elsif status == "available"
      @be_reported_users = @be_reported_users.where("is_blocked = false");
    end

    if order == "asc"
      @be_reported_users = @be_reported_users.order("COUNT(reports.reported_id) ASC");
    elsif order == "desc"
      @be_reported_users = @be_reported_users.order("COUNT(reports.reported_id) DESC");
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :check_blocked_user, :logged_in_user, only: %i(create)

  def create
    @report = Report.new report_params.merge(user: current_user)
    if @report.save
      @status = true
    else
      @status = false
    end

    respond_to do |format|
      format.js {}
    end
  end

  private
  def report_params
    params.require(:report).permit Report::ATTRIBUTES_PARAMS
  end
end

app/views/admin/reports/index.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin/admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.description" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @be_reported_users.each do |report| %>
          <tr>
            <td><%= report.id %></td>
            <td>
              <% if report.is_blocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= report.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= report.description %></td>
            <td><%= report.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td>
              <%= link_to t("admin.detail"), admin_report_path(report.user_id) %>
              <%= link_to t("edit"), edit_user_path(report.reported_id) %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination -->
    <%= paginate @be_reported_users %>
  </div>
</div>
</div>
</div>

app/views/admin/reports/show.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin/admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th>
            <% if params[:order] == "asc" %>
              <%= link_to t("admin.count"), params.merge(order: "desc") %>
            <% else  %>
              <%= link_to t("admin.count"), params.merge(order: "asc") %>
            <% end %>
          </th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @report.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <% if user.is_blocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= user.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td><%= user.total %></td>
            <td><%= link_to t(".edit"), edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
</div>

app/views/admin/reports/show_unique_reports.html.erb
<div id="page-contents">
<div class="container">
<div class="row">

  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "shared/current_user_profile_card" %>
    <%= render "admin/admin_nav" %>
  </div>
  <div class="col-md-9">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <% if params[:status] != "blocked" %>
              <%= link_to t("admin.status"), params.merge(status: "blocked") %>
            <% else %>
              <%= link_to t("admin.status"), params.merge(status: "available") %>
            <% end %>
          </th>
          <th><%= t "admin.name" %></th>
          <th><%= t "admin.avatar" %></th>
          <th><%= t "admin.reported_at" %></th>
          <th>
            <% if params[:order] == "desc" %>
              <%= link_to t("admin.count"), params.merge(order: "asc") %>
            <% else  %>
              <%= link_to t("admin.count"), params.merge(order: "desc") %>
            <% end %>
          </th>
          <th><%= t "admin.action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @be_reported_users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <% if user.is_blocked? %>
                <span class="label label-danger"><%= t "admin.blocked" %></span>
              <% else %>
                <span class="label label-success"><%= t "admin.available" %></span>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= image_tag("users/user-1.jpg", :class => "profile-photo-admin") %></td>
            <td><%= user.created_at.strftime("%d/%m/%y %I:%M") %></td>
            <td><%= user.total %></td>
            <td><%= link_to t(".edit"), edit_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination -->
    <%= paginate @be_reported_users %>
  </div>
</div>
</div>
</div>